### ISSUE TITLE
linum mode margin left to wide

### ISSUE THREAD

**Issue by ExternalReality** [jimeh/birds-of-paradise-plus-theme.el#2]
When using this theme the left margin is too great. Given a small file (say 20 lines) the area with the number can fit a number several hundred times larger than the numbers on the screen when linum mode is enabled. Thank you for your help. Nice theme.

**Comment by jimeh** [comment]
I don't think the margin has anything to do with the theme, as it literally only sets face colors. If I'm wrong, please feel free to elaborate and reopen this issue.
